# An analysis of African countries by GDP in 2022

# 1. Introduction
## GDP is defined as the "total monetary or market value of all the finished 
## goods and services produced within a country’s borders in a specific time period"

# (A) Load the required libraries

library(tidyverse)
library(rvest)
library(stringr)
library(janitor)
library(gghighlight)
library(readr)

# (B) New method to export images and gifs

# To export the images
# camcorder::gg_record()

library(camcorder)

gg_record(
  dir = 'sub_pro_5_africa_economy/images',
  width = 12,
  height = 12 ,
  dpi = 300,
  bg = 'white'
)

# (C) Get the data from Wikipedia

link <- "https://en.wikipedia.org/wiki/List_of_African_countries_by_GDP_(nominal)"
africa_country <- link %>%
  read_html("[class='wikitable sortable']") %>% 
  html_table(fill = TRUE)

africa_country_GDP <- africa_country[[1]]

# (D) Clean the data, fix columns and county labels

africa_country_GDP_clean <- africa_country_GDP %>%
  clean_names() %>%
  filter(country != "Total") %>%
  rename("nominal_gdp" = "nominal_gdp_billion_us_8_9",
         "gdp_per_capita" = "per_capita_us_8_9")

# parsing out the number is very critical as a simple conversion using 
# as._____() will not work

str(africa_country_GDP_clean)

africa_country_GDP_clean$nominal_gdp <- parse_number(africa_country_GDP_clean$nominal_gdp)
africa_country_GDP_clean$gdp_per_capita <- parse_number(africa_country_GDP_clean$gdp_per_capita)

# Nominal GDP table

africa_country_GDP_clean_1 <- subset(africa_country_GDP_clean, select = -gdp_per_capita)
str(africa_country_GDP_clean_1)

# Per capita table 

africa_country_GDP_clean_2 <- subset(africa_country_GDP_clean, select = -nominal_gdp)
str(africa_country_GDP_clean_1)

# (E) Plots

## 1) A bar plot demonstrating the GDP of the top 5 economies relative to the rest of the continent

ggplot(africa_country_GDP_clean_1, aes(reorder(country, +nominal_gdp), nominal_gdp, fill = country)) +
  geom_bar(stat = "identity") + coord_flip() +
  gghighlight(max(nominal_gdp) > 140) + 
  scale_fill_brewer(palette="OrRd") +
  labs(x = "Country",
       y = "GDP (billions of US$)",
       title = "Majority of Africa's GDP in 2022 was generated by 5 countries",
       subtitle = "",
       caption = "Data Source: Wikipedia | By @willyokech") +
  theme_classic() +
  scale_y_continuous(labels = comma) +
  theme(axis.title.x =element_text(size = 20),
        axis.title.y =element_text(size = 20),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 15),
        plot.title = element_text(family="Helvetica", face="bold", size = 25, hjust = 1.5, vjust=0.5),
        plot.subtitle = element_text(family="Helvetica", face="bold", size = 20),
        plot.caption = element_text(family = "Helvetica",size = 15, face = "bold"),
        plot.background = element_rect(fill = "azure2", colour = "azure2"),
        panel.background = element_rect(fill = "azure2", colour = "azure2"),
        legend.title = element_blank(),
        legend.position = "none") 

## 2) A tree map demonstrating the GDP of the top 5 economies relative to the rest of the continent

# Get the top 5 economies
africa_country_GDP_clean_top_5 <- africa_country_GDP_clean_1[1:5, ]

# Get the bottom 49
africa_country_GDP_clean_bottom <- africa_country_GDP_clean_1[africa_country_GDP_clean_1$nominal_gdp < 130, ]

# Sum the bottom 49
africa_country_GDP_clean_bottom_total <- africa_country_GDP_clean_bottom %>%
  bind_rows(summarise(., across(where(is.numeric), sum),
                      across(where(is.character), ~'Rest of the Continent'))) %>%
  filter(row_number() %in% 50)

# Combine the top 5 economies with the combined GDP of the other 49 countries
africa_country_GDP_clean_top_5_bottom_total <- rbind(africa_country_GDP_clean_top_5, 
                                                     africa_country_GDP_clean_bottom_total)

# Create new columns to provide labels for the treemap
africa_country_GDP_clean_top_5_bottom_total_new_col <- africa_country_GDP_clean_top_5_bottom_total %>%
  mutate(nominal_gdp_new_1 = paste("$", nominal_gdp, sep = "")) %>%
  mutate(nominal_gdp_new_2 = paste(nominal_gdp_new_1, "Billion", sep = " ")) 

# Plot the tree map
ggplot(africa_country_GDP_clean_top_5_bottom_total_new_col, 
       aes(area = nominal_gdp, fill = country, 
           label = paste(country, nominal_gdp_new_2, sep = "\n"))) +
  geom_treemap() +
  labs(title = "Over half of Africa's GDP is generated by 5 countries",
       subtitle = "Nigeria, Egypt, South Africa, Algeria, and Morocco account for about 58% of Africa's GDP in 2022",
       fill = "",
       caption = "Data Source: Wikipedia | By @willyokech") +
  geom_treemap_text(colour = "black",
                    place = "centre",
                    size = 30,
                    grow = FALSE) + 
  theme(legend.position = "bottom",
        plot.title = element_text(size=30),
        plot.subtitle = element_text(size=15),
        legend.text = element_text(size = 20),
        plot.caption = element_text(size = 15),
        panel.background = element_rect(fill="azure2"),
        plot.background = element_rect(fill="azure2"),
        legend.background = element_rect(fill="azure2")) +
  scale_fill_brewer(palette = "Oranges")

## 3) A bar plot to compare the GDP per capita of African countries

ggplot(africa_country_GDP_clean_2, aes(reorder(country, +gdp_per_capita), gdp_per_capita, fill = country)) +
  geom_bar(stat = "identity") + coord_flip() +
  gghighlight(max(gdp_per_capita) > 10000) + 
  scale_fill_brewer(palette="OrRd") +
  labs(x = "Country",
       y = "GDP per capita (US$)",
       title = "Only 3 countries in Africa were part of the $10k or greater club",
       subtitle = "Majority of the countries had GDPs per capita below $1500",
       caption = "Data Source: Wikipedia | By @willyokech") +
  theme_classic() +
  scale_y_continuous(labels = comma) +
  theme(axis.title.x =element_text(size = 20),
        axis.title.y =element_text(size = 20),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 15),
        plot.title = element_text(family="Helvetica", face="bold", size = 25, hjust = 1.5, vjust=0.5),
        plot.subtitle = element_text(family="Helvetica", size = 20, hjust = -1.5, vjust=0.5),
        plot.caption = element_text(family = "Helvetica",size = 15, face = "bold"),
        plot.background = element_rect(fill = "azure2", colour = "azure2"),
        panel.background = element_rect(fill = "azure2", colour = "azure2"),
        legend.title = element_blank(),
        legend.position = "none") 

## 4) Scatter plot to compare GDP per capita, population size, and nominal GDP

# Import the required data from Wikipedia

link_pop <- "https://en.wikipedia.org/wiki/List_of_African_countries_by_population"
africa_country_pop <- link_pop %>%
  read_html("[class='wikitable sortable']") %>% 
  html_table(fill = TRUE)

africa_country_pop_1 <- africa_country_pop[[1]]

# Clean the data, fix columns and county labels

africa_country_pop_1_clean <- africa_country_pop_1 %>%
  clean_names() %>%
  select(c(country, africapopulation_4)) %>%
  filter(country != "Total") %>%
  rename("population" = "africapopulation_4")

# parsing out the number is very critical as a simple conversion using 
# as._____() will not work

str(africa_country_pop_1_clean)

africa_country_pop_1_clean$population <- parse_number(africa_country_pop_1_clean$population)

str(africa_country_pop_1_clean)

africa_country_pop_1_clean[africa_country_pop_1_clean=="DR Congo"] <- "Democratic Republic of the Congo"
africa_country_pop_1_clean[africa_country_pop_1_clean=="Congo"] <- "Republic of Congo"
africa_country_pop_1_clean[africa_country_pop_1_clean=="Gambia"] <- "The Gambia"

# Join the tables 

africa_country_GDP_pop <- left_join(africa_country_GDP_clean, africa_country_pop_1_clean, by = "country")

# Basic bubble plot / ####### Not very useful #########

ggplot(africa_country_GDP_pop, aes(x=gdp_per_capita, y=nominal_gdp, size = population)) +
  geom_point(alpha=0.7) +
  scale_size(range = c(5, 24), name="Population (M)")
